### ISSUE TITLE
'다양한 문제집 보러 가기' 첫 화면에 다양한 문제집이 보이면 좋을거 같아요

### ISSUE THREAD

**Issue by Hyeon9mak** [woowacourse-teams/2021-botobo#425]
![image](https://user-images.githubusercontent.com/37354145/130590082-40fcfd58-31aa-4489-ad96-a94793dd3863.png)

비로그인 상태에서 '다양한 문제집 보러 가기'를 클릭 했을 때

- 다른 사람들이 많이 봤던 문제집
- 최근에 추가된 문제집
- 추천 태그로 필터링 된 문제집

등이 보이길 기대했는데요,

![image](https://user-images.githubusercontent.com/37354145/130590095-e62a0e8e-6feb-4ce5-8908-8bae4fb20e10.png)

실제 화면에는 아무것도 출력되지 않아 '로딩중인가?' 라는 생각이 들었어요.

자동으로 추천 문제집 이름, 추천 태그등이 입력된 상태의 화면을 보여주는 것도 좋을거 같아요!

**Comment by pkeugine** [comment]
확실히 사진과 함께 피드백을 읽어보니 검색 첫 화면이 비어있다는 느낌이 드네요.
피드백 감사합니다! 반영해서 팀원들과 상의해보도록 할게요 👍

**Comment by seovalue** [comment]
이
