### ISSUE TITLE
B10 - letsencrypt 인증서가 3개월 주기로 만료되는 문제 해결

### ISSUE THREAD

**Issue by seovalue** [woowacourse-teams/2021-botobo#533]
- [ ] crontab을 활용하여 인증서 만료 문제를 해결한다.

* 참고 자료
  * https://ksbgenius.github.io/ssl/2020/11/01/letsencrypt-certificates-auto-renewal.html
  * http://sharpbasket.com/lets-encrypt-ssl-%EC%9D%B8%EC%A6%9D%EC%84%9C-%EC%9E%90%EB%8F%99-%EA%B0%B1%EC%8B%A0/

---

* develop 만료일: 2021년 10월 6일
```
[DEVELOP-SERVER][00:56:21][ubuntu@ip-192-168-1-36 ~]
$ echo | openssl s_client -connect ip-192-168-1-36:443 2>/dev/null | openssl x509 -noout -dates
notBefore=Jul  8 04:04:21 2021 GMT
notAfter=Oct  6 04:04:20 2021 GMT
```
* main 만료일: 2021년 11월 22일
```
[REVERSE-PROXY][00:58:31][ubuntu@ip-192-168-1-44 ~]
$ echo | openssl s_client -connect ip-192-168-1-44:443 2>/dev/null | openssl x509 -noout -dates
notBefore=Aug 24 04:43:18 2021 GMT
notAfter=Nov 22 04:43:17 2021 GMT
```

**Comment by seovalue** [comment]
서브도메인 관련 인증서 재발급으로 인증서 유효기간이 12/30로 늘어났습니다.
+ https://joanne.tistory.com/271 이유로 해당 이슈 클로즈합니다!

**Comment by pkeugine** [comment]
넵! 공휴일에 고생하셨습니다!! 😁
