### ISSUE TITLE
B20 - git 서브모듈을 이용하여 민감한 정보를 관리한다

### ISSUE THREAD

**Issue by pkeugine** [woowacourse-teams/2021-botobo#80]

**Comment by ggyool** [comment]
![1](https://user-images.githubusercontent.com/12393067/125896891-e72bce57-18a8-43fc-9a68-549bed652a3c.png)
![2](https://user-images.githubusercontent.com/12393067/125897007-4e5bd29c-2201-4923-a33f-25597068e9a4.png)
![3](https://user-images.githubusercontent.com/12393067/125898012-e63375e4-a0bf-4cdb-bea2-792382e17771.png)

**Comment by ggyool** [comment]
<img width="940" alt="4" src="https://user-images.githubusercontent.com/12393067/125898153-aa984b17-a0e0-4537-8db3-06d330082a2a.png">
![5](https://user-images.githubusercontent.com/12393067/125898285-3d02beb4-32f1-4926-8782-0a9339bbed95.png)
![6](https://user-images.githubusercontent.com/12393067/125898362-7fcc0d2d-307e-457b-9bb8-b16d53565e97.png)
<img width="1722" alt="7" src="https://user-images.githubusercontent.com/12393067/125898503-5712fa19-c118-45e5-a8a6-de1a30df3040.png">
